org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024M -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx2048M
android.enableJetifier=true
android.useAndroidX=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
