// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi8eGLyGHF7s4Dv42N_4RpiY-GaLsNc7s',
    appId: '1:1001853874812:web:c3654174396797a647cff9',
    messagingSenderId: '1001853874812',
    projectId: 'athlorun',
    authDomain: 'athlorun.firebaseapp.com',
    storageBucket: 'athlorun.firebasestorage.app',
    measurementId: 'G-NSNWDHXC04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe-tAN9UgIIh2O_Y3z614PXHmHAjFOQ1s',
    appId: '1:1001853874812:android:a1cfcb42ffb7807c47cff9',
    messagingSenderId: '1001853874812',
    projectId: 'athlorun',
    storageBucket: 'athlorun.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBl81DP7mpjwY-MBmhZPeTUhgyj7UXdb4',
    appId: '1:1001853874812:ios:40ce3113cad0237d47cff9',
    messagingSenderId: '1001853874812',
    projectId: 'athlorun',
    storageBucket: 'athlorun.firebasestorage.app',
    iosBundleId: 'com.example.athlorun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBl81DP7mpjwY-MBmhZPeTUhgyj7UXdb4',
    appId: '1:1001853874812:ios:40ce3113cad0237d47cff9',
    messagingSenderId: '1001853874812',
    projectId: 'athlorun',
    storageBucket: 'athlorun.firebasestorage.app',
    iosBundleId: 'com.example.athlorun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi8eGLyGHF7s4Dv42N_4RpiY-GaLsNc7s',
    appId: '1:1001853874812:web:7c4d4de478abbd4647cff9',
    messagingSenderId: '1001853874812',
    projectId: 'athlorun',
    authDomain: 'athlorun.firebaseapp.com',
    storageBucket: 'athlorun.firebasestorage.app',
    measurementId: 'G-TEPV16P0R9',
  );
}
